web-server:
  build: .
  ports:
   - 80:3000
  links:
   - data-cache
   - rt-database
  volumes:
   - .:/usr/src/app
  command: npm run dev

app-service:
  image: almanac/app-service:dev
  links:
   - data-cache
   - rt-database
  restart: always

rt-database:
  image: rethinkdb
  ports:
   - 8080:8080
  volumes_from:
   - rtdb

data-cache:
  image: redis
  volumes_from:
    - cachedb
  command: redis-server --appendonly yes
