web-server:
  image: almanac/web-server:dev
  ports:
   - 80:3000
  restart: always
  links:
   - data-cache
   - rt-database
  volumes:
   - .:/usr/src/app
  command: npm run dev

app-service:
  image: almanac/app-service:dev
  restart: always
  links:
  - data-cache
  - rt-database
  environment:
   - USERID=natejlevine@gmail.com
   - PASSWORD=monkeybisness
   - BITLY_TOKEN=ab6dbf0df548c91cffaa1ae82e0d9f4a52dfe4f8
   - NYT_KEY=202f0d73b368cec23b977f5a141728ce:17:73664181

rt-database:
  image: rethinkdb
  ports:
   - 8080:8080
  volumes_from:
   - rtdb

data-cache:
  image: redis
  volumes_from:
    - cachedb
  command: redis-server --appendonly yes
