web-server:
  image: almanac/web-server:dev
  ports:
   - 80:3000
  restart: always
  links:
   - data-cache
   - rt-database
  volumes:
   - .:/usr/src/app
  command: npm run dev

app-service:
  image: almanac/app-service:dev
  restart: always
  links:
  - data-cache
  - rt-database
  environment:
   - USERID=USERID
   - PASSWORD=PASSWORD
   - BITLY_TOKEN=TOKEN
   - NYT_KEY=KEY

rt-database:
  image: rethinkdb
  ports:
   - 8080:8080
  volumes_from:
   - rtdb

data-cache:
  image: redis
  volumes_from:
    - cachedb
  command: redis-server --appendonly yes
