web-server:
  image: almanac/web-server:dev
  ports:
   - 80:3000
  links:
   - app-service
   - data-cache

app-service:
  image: almanac/app-service:redis
  links:
    - data-cache

data-cache:
  image: redis
  volumes_from:
    - cachedb
  command: redis-server --appendonly yes
